Update dev-setup.md
Wont compile without missing Rustls backend dependency of either rustls-aws-lc or rustls-ring.

Removing hickory from install argument because of error in compile time.

```
error: none of the selected packages contains this feature: hickory
selected packages: g3bench, g3fcgen, g3iploc, g3keymess, g3keymess-proto, g3keymess-ctl, g3mkcert, g3proxy, g3proxy-ctl, g3proxy-ftp, g3proxy-lua, g3statsd, g3statsd-ctl, g3tiles, g3tiles-ctl, capnp-generate
help: package with the missing feature: g3-resolver
```